import Navbar from "@/Components/Navbar";
import Head from "next/head";
import dynamic from "next/dynamic";


import { motion, AnimatePresence } from 'framer-motion';


function Layout({ children, router }) {
    return (
        <>
            <Head>
                <title>Space tourism website</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body>
                <AnimatePresence mode="wait">
                    <div key={router.pathname}>
                        <Navbar />
                        <motion.main
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            transition={{ duration: 0.5, ease: 'easeInOut' }}
                            exit={{opacity: 0}}
                        >
                            {children}
                        </motion.main>
                    </div>
                </AnimatePresence>
            </body>
        </>
    )
}

export default dynamic(() => Promise.resolve(Layout), { ssr: false })
